/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcf1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
echo_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		echos get_echo_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_echo:
		_xdr_argument = (xdrproc_t) xdr_echos;
		_xdr_result = (xdrproc_t) xdr_echos;
		local = (char *(*)(char *, struct svc_req *)) get_echo_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
sort_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		sorts get_sort_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_sort:
		_xdr_argument = (xdrproc_t) xdr_sorts;
		_xdr_result = (xdrproc_t) xdr_sorts;
		local = (char *(*)(char *, struct svc_req *)) get_sort_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
readdirp_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dirs get_readdirp_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_readdirp:
		_xdr_argument = (xdrproc_t) xdr_dirs;
		_xdr_result = (xdrproc_t) xdr_dirs;
		local = (char *(*)(char *, struct svc_req *)) get_readdirp_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
time_prog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		timeint get_time_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_time:
		_xdr_argument = (xdrproc_t) xdr_timeint;
		_xdr_result = (xdrproc_t) xdr_timeint;
		local = (char *(*)(char *, struct svc_req *)) get_time_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
matmul_prog_5(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		arrs get_matmul_5_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_matmul:
		_xdr_argument = (xdrproc_t) xdr_arrs;
		_xdr_result = (xdrproc_t) xdr_arrs;
		local = (char *(*)(char *, struct svc_req *)) get_matmul_5_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (ECHO_PROG, ECHO_VERS);
	pmap_unset (SORT_PROG, SORT_VERS);
	pmap_unset (readdirp_PROG, readdirp_VERS);
	pmap_unset (TIME_PROG, TIME_VERS);
	pmap_unset (MATMUL_PROG, MATMUL_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ECHO_PROG, ECHO_VERS, echo_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ECHO_PROG, ECHO_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SORT_PROG, SORT_VERS, sort_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SORT_PROG, SORT_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, readdirp_PROG, readdirp_VERS, readdirp_prog_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (readdirp_PROG, readdirp_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, TIME_PROG, TIME_VERS, time_prog_4, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TIME_PROG, TIME_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MATMUL_PROG, MATMUL_VERS, matmul_prog_5, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MATMUL_PROG, MATMUL_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ECHO_PROG, ECHO_VERS, echo_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ECHO_PROG, ECHO_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SORT_PROG, SORT_VERS, sort_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SORT_PROG, SORT_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, readdirp_PROG, readdirp_VERS, readdirp_prog_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (readdirp_PROG, readdirp_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, TIME_PROG, TIME_VERS, time_prog_4, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TIME_PROG, TIME_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MATMUL_PROG, MATMUL_VERS, matmul_prog_5, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MATMUL_PROG, MATMUL_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
