/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpcf1.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct echos *
get_echo_1(echos *argp, CLIENT *clnt)
{
	static struct echos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_echo,
		(xdrproc_t) xdr_echos, (caddr_t) argp,
		(xdrproc_t) xdr_echos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct sorts *
get_sort_2(sorts *argp, CLIENT *clnt)
{
	static struct sorts clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_sort,
		(xdrproc_t) xdr_sorts, (caddr_t) argp,
		(xdrproc_t) xdr_sorts, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct dirs *
get_readdirp_3(dirs *argp, CLIENT *clnt)
{
	static struct dirs clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_readdirp,
		(xdrproc_t) xdr_dirs, (caddr_t) argp,
		(xdrproc_t) xdr_dirs, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct timeint *
get_time_4(timeint *argp, CLIENT *clnt)
{
	static struct timeint clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_time,
		(xdrproc_t) xdr_timeint, (caddr_t) argp,
		(xdrproc_t) xdr_timeint, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct arrs *
get_matmul_5(arrs *argp, CLIENT *clnt)
{
	static struct arrs clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_matmul,
		(xdrproc_t) xdr_arrs, (caddr_t) argp,
		(xdrproc_t) xdr_arrs, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
