/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCF1_H_RPCGEN
#define _RPCF1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct echos {
	char message[100];
};
typedef struct echos echos;

struct sorts {
	int sa[100];
	int size;
};
typedef struct sorts sorts;

struct dirs {
	char filearr1[25];
	char filearr2[25];
	char filearr3[25];
	char filearr4[25];
	char filearr5[25];
	char filearr6[25];
	char filearr7[25];
	char filearr8[25];
	char filearr9[25];
	char filearr10[25];
	char filearr11[25];
	char filearr12[25];
	char filearr13[25];
	char filearr14[25];
	char filearr15[25];
	char filearr16[25];
	int count;
};
typedef struct dirs dirs;

struct timeint {
	int year;
	int month;
	int day;
	int hour;
	int min;
	int sec;
};
typedef struct timeint timeint;

struct arrs {
	int a1[2];
	int a2[2];
	int b1[2];
	int b2[2];
	int c1[2];
	int c2[2];
};
typedef struct arrs arrs;

#define ECHO_PROG 0x31111112
#define ECHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_echo 1
extern  struct echos * get_echo_1(echos *, CLIENT *);
extern  struct echos * get_echo_1_svc(echos *, struct svc_req *);
extern int echo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_echo 1
extern  struct echos * get_echo_1();
extern  struct echos * get_echo_1_svc();
extern int echo_prog_1_freeresult ();
#endif /* K&R C */

#define SORT_PROG 0x31111122
#define SORT_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define get_sort 1
extern  struct sorts * get_sort_2(sorts *, CLIENT *);
extern  struct sorts * get_sort_2_svc(sorts *, struct svc_req *);
extern int sort_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_sort 1
extern  struct sorts * get_sort_2();
extern  struct sorts * get_sort_2_svc();
extern int sort_prog_2_freeresult ();
#endif /* K&R C */

#define readdirp_PROG 0x31111222
#define readdirp_VERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define get_readdirp 1
extern  struct dirs * get_readdirp_3(dirs *, CLIENT *);
extern  struct dirs * get_readdirp_3_svc(dirs *, struct svc_req *);
extern int readdirp_prog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_readdirp 1
extern  struct dirs * get_readdirp_3();
extern  struct dirs * get_readdirp_3_svc();
extern int readdirp_prog_3_freeresult ();
#endif /* K&R C */

#define TIME_PROG 0x31112222
#define TIME_VERS 4

#if defined(__STDC__) || defined(__cplusplus)
#define get_time 1
extern  struct timeint * get_time_4(timeint *, CLIENT *);
extern  struct timeint * get_time_4_svc(timeint *, struct svc_req *);
extern int time_prog_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_time 1
extern  struct timeint * get_time_4();
extern  struct timeint * get_time_4_svc();
extern int time_prog_4_freeresult ();
#endif /* K&R C */

#define MATMUL_PROG 0x31122222
#define MATMUL_VERS 5

#if defined(__STDC__) || defined(__cplusplus)
#define get_matmul 1
extern  struct arrs * get_matmul_5(arrs *, CLIENT *);
extern  struct arrs * get_matmul_5_svc(arrs *, struct svc_req *);
extern int matmul_prog_5_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_matmul 1
extern  struct arrs * get_matmul_5();
extern  struct arrs * get_matmul_5_svc();
extern int matmul_prog_5_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_echos (XDR *, echos*);
extern  bool_t xdr_sorts (XDR *, sorts*);
extern  bool_t xdr_dirs (XDR *, dirs*);
extern  bool_t xdr_timeint (XDR *, timeint*);
extern  bool_t xdr_arrs (XDR *, arrs*);

#else /* K&R C */
extern bool_t xdr_echos ();
extern bool_t xdr_sorts ();
extern bool_t xdr_dirs ();
extern bool_t xdr_timeint ();
extern bool_t xdr_arrs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCF1_H_RPCGEN */
