/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcf1.h"
#include <dirent.h>
#include <string.h>
#include <stdio.h>
#include <time.h>

struct echos *
get_echo_1_svc(echos *argp, struct svc_req *rqstp)
{
	static struct echos  result;

	/*Storing the user message into result and returning*/
        result=*argp;
	return &result;
}

struct sorts *
get_sort_2_svc(sorts *argp, struct svc_req *rqstp)
{
	static struct sorts  result;
        int temp,swap,i;
	/*Storing the user sent data into result and then accessing it */
        result=*argp;
        
        /*Bubble Sort function*/
        swap=1;
        int j=0;
        while(swap==1)
        {
        swap=0;
        j++;
        for(i=0;i<result.size-j;i++)
        {
        if(result.sa[i]>result.sa[i+1])
        {
        temp=0;
        temp=result.sa[i];
        result.sa[i]=result.sa[i+1];
        result.sa[i+1]=temp;
        swap=1;
        }
        }
        }
	return &result;
}

struct dirs *
get_readdirp_3_svc(dirs *argp, struct svc_req *rqstp)
{
	static struct dirs  result;
    /*the arrays using pointers which will store the filenames*/
    char* filearr1p; 
    char* filearr2p;
    char* filearr3p;
    char* filearr4p;
    char* filearr5p;
    char* filearr6p;
    char* filearr7p;
    char* filearr8p;
    char* filearr9p;
    char* filearr10p;
    char* filearr11p;
    char* filearr12p;
    char* filearr13p;
    char* filearr14p;
    char* filearr15p;
    char* filearr16p;
    result=*argp;

	
    DIR *dir;
    result.count=0;
    struct dirent *ent;
    dir = opendir (".");
    if (dir != NULL) 
    {
    /* copy all the files and directories within directory */
    while ((ent = readdir (dir)) != NULL&& result.count<16) 
        {
        if(result.count==0){
        filearr1p=ent->d_name;
        strncpy (result.filearr1, filearr1p , 25);
        /* save filenames in the array of result*/
        result.count++;
        }
        else if(result.count==1){
        filearr2p=ent->d_name;
        strncpy (result.filearr2, filearr2p , 25);
        result.count++;
        }
         else if(result.count==2){
        filearr3p=ent->d_name;
        strncpy (result.filearr3, filearr3p , 25);
        result.count++;
        }
         else if(result.count==3){
        filearr4p=ent->d_name;
        strncpy (result.filearr4, filearr4p , 25);
        result.count++;
        }
         else if(result.count==4){
        filearr5p=ent->d_name;
        strncpy (result.filearr5, filearr5p , 25);
        result.count++;
        }
         else if(result.count==5){
        filearr6p=ent->d_name;
        strncpy (result.filearr6, filearr6p , 25);
        result.count++;
        }
          else if(result.count==6){
        filearr7p=ent->d_name;
       strncpy (result.filearr7, filearr7p , 25);
        result.count++;
        }
          else if(result.count==7){
        filearr8p=ent->d_name;
        strncpy (result.filearr8, filearr8p , 25);
        result.count++;
        }
          else if(result.count==8){
        filearr9p=ent->d_name;
        strncpy (result.filearr9, filearr9p , 25);
        result.count++;
        }
         else if(result.count==9){
        filearr10p=ent->d_name;
        strncpy (result.filearr10, filearr10p , 25);
        result.count++;
        }
         else if(result.count==10){
        filearr11p=ent->d_name;
        strncpy (result.filearr11, filearr11p , 25);
        result.count++;
        }
         else if(result.count==11){
        filearr12p=ent->d_name;
        strncpy (result.filearr12, filearr12p , 25);
        result.count++;
        }
          else if(result.count==12){
        filearr13p=ent->d_name;
        strncpy (result.filearr13, filearr13p , 25);
        result.count++;
        }
          else if(result.count==13){
        filearr14p=ent->d_name;
        strncpy (result.filearr14, filearr14p , 25);
        result.count++;
        }
          else if(result.count==14){
        filearr15p=ent->d_name;
        strncpy (result.filearr15, filearr15p , 25);
        result.count++;
        }
         else {
        filearr16p=ent->d_name;
        strncpy (result.filearr16, filearr16p , 25);
        result.count++;
        }
        }
    closedir (dir);
    } 
    else
    {
    /* error specifying could not open directory */
    perror ("");
    }
	return &result;
}

struct timeint *
get_time_4_svc(timeint *argp, struct svc_req *rqstp)
{
       
	static struct timeint  result;
       /*using time.h functions and storing the date and time details accordingly*/
        time_t t=time(NULL);
        struct tm t1=*localtime(&t);
        result.year=t1.tm_year+1900;
        result.month=t1.tm_mon+1;
        result.day=t1.tm_mday;
        result.hour=t1.tm_hour;
        result.min=t1.tm_min;
        result.sec=t1.tm_sec;

	return &result;
}

struct arrs *
get_matmul_5_svc(arrs *argp, struct svc_req *rqstp)
{
	static struct arrs  result;
         result=*argp;
        int i,j,k,sum;
        sum=0;

        /*Matrix Multiplication*/
         for(i=0;i<2;i++)
        {
         if(i==0){/*For first row of result matrix*/
          for(k=0;k<2;k++)
           {
            if(k==0){/*For first row first element of result matrix*/
             for(j=0;j<2;j++)
              {
               sum=sum+(result.a1[j]*result.b1[j]);
              }
             result.c1[k]=sum;
             sum=0;
            }
            else{/*For first row second element of result matrix*/
             for(j=0;j<2;j++)
             {
              sum=sum+(result.a1[j]*result.b2[j]);
             }
              result.c1[k]=sum;
              sum=0;
            }/*end else k*/
           }/*end for k*/
          }/*end if i*/
          else{/*For second row of result matrix*/
           for(k=0;k<2;k++)
            {
             if(k==0){/*For second row first element of result matrix*/
              for(j=0;j<2;j++)
               {
                sum=sum+(result.a2[j]*result.b1[j]);
               }
              result.c2[k]=sum;
              sum=0;
              }
             else{/*For second row second element of result matrix*/
              for(j=0;j<2;j++)
               {
                sum=sum+(result.a2[j]*result.b2[j]);
               }
              result.c2[k]=sum;
              sum=0;
             }
            }/*end else k*/
           }/*end else i*/
          }/*end for i*/

	return &result;
}
